apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  labels:
    app: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: web-app-pod
      app: web-app
  template:
    metadata:
      name: web-app-pod
      labels:
        name: web-app-pod
        app: web-app
        
    spec:
      containers:
      - name: web-app
        image: tanvir0102/mediawiki:latest
        ports:
        - containerPort: 80